name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service
    steps:
      - uses: actions/checkout@v4

      - name: Debug Directory Contents
        run: |
          pwd
          ls -la

      - name: Debug File Permissions Before
        run: |
          ls -l mvnw || echo "mvnw not found"
          file mvnw || echo "mvnw not accessible"

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Debug File Permissions After
        run: |
          ls -l mvnw
          file mvnw

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify
